# Generated by Django 2.2.3 on 2019-08-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0002_auto_20190804_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('alpha3Code',)},
        ),
    ]
