# Generated by Django 2.2.3 on 2019-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0002_auto_20190729_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='leavingDate',
            field=models.DateTimeField(null=True, verbose_name='When the rider leaves the team'),
        ),
    ]
