# Generated by Django 2.2.3 on 2019-07-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0003_auto_20190729_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='leavingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When the rider leaves the team'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('time', models.TimeField(null=True)),
                ('stagePoints', models.IntegerField(null=True)),
                ('sprintPoints', models.IntegerField(null=True)),
                ('komPoints', models.IntegerField(null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='stage',
            field=models.ManyToManyField(related_name='_rider_stage_+', through='Cycl.Result', to='Cycl.Stage'),
        ),
    ]
