# Generated by Django 2.2.3 on 2019-07-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0004_auto_20190729_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Rider')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='race',
            field=models.ManyToManyField(related_name='_rider_race_+', through='Cycl.Register', to='Cycl.Race'),
        ),
    ]
