# Generated by Django 2.2.3 on 2019-08-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0004_auto_20190804_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Team'),
        ),
    ]
