# Generated by Django 2.2.3 on 2019-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0005_auto_20190804_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='nation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
