# Generated by Django 2.2.3 on 2019-07-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0005_auto_20190729_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atStart', models.BooleanField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='startList',
            field=models.ManyToManyField(related_name='_rider_startList_+', through='Cycl.StartList', to='Cycl.Stage'),
        ),
    ]
