# Generated by Django 2.2.3 on 2019-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0006_auto_20190729_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startlist',
            name='atStart',
            field=models.BooleanField(default=1),
        ),
    ]
