# Generated by Django 2.2.3 on 2019-08-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0006_auto_20190804_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='nation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cycl.Team'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cycl.Team'),
        ),
    ]
