# Generated by Django 2.2.3 on 2019-07-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0007_auto_20190729_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlist',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
