# Generated by Django 2.2.3 on 2019-08-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0007_auto_20190804_2220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set(),
        ),
    ]
