# Generated by Django 2.2.3 on 2019-07-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0008_startlist_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startlist',
            unique_together={('stage', 'rider')},
        ),
    ]
