# Generated by Django 2.2.3 on 2019-08-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0009_auto_20190804_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='continent',
        ),
        migrations.AlterField(
            model_name='rider',
            name='nation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cycl.Country'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cycl.Country'),
        ),
    ]
