# Generated by Django 2.2.3 on 2019-07-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0009_auto_20190729_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('race', 'rider')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('stage', 'rider')},
        ),
    ]
