# Generated by Django 2.2.3 on 2019-07-30 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0010_auto_20190729_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=150)),
                ('playerName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('isPremium', models.BooleanField(default=0)),
                ('lastLogin', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 9, 55, 15, 811027, tzinfo=utc))),
            ],
            options={
                'ordering': ['lastName', 'firstName'],
            },
        ),
        migrations.AlterField(
            model_name='lineup',
            name='arrivalDate',
            field=models.DateTimeField(verbose_name='Rider arrives in team'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='leavingDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rider leaves the team'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Player')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Rider')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Stage')),
            ],
            options={
                'unique_together': {('player', 'stage', 'rider')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='rider',
            field=models.ManyToManyField(related_name='_player_rider_+', through='Cycl.Roster', to='Cycl.Rider'),
        ),
        migrations.AddField(
            model_name='player',
            name='stage',
            field=models.ManyToManyField(related_name='_player_stage_+', through='Cycl.Roster', to='Cycl.Stage'),
        ),
    ]
