# Generated by Django 2.2.3 on 2019-07-30 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Cycl', '0011_auto_20190730_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stage',
        ),
        migrations.AlterField(
            model_name='player',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 12, 30, 35, 680686, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rosterTotalTime', models.TimeField(null=True)),
                ('rosterRank', models.IntegerField()),
                ('rosterPointsEarned', models.IntegerField()),
                ('additionnalPoints', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Player')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycl.Stage')),
            ],
            options={
                'unique_together': {('player', 'stage')},
            },
        ),
    ]
